using System.Collections.Generic;
using Backend.Controllers;
using Xunit;

namespace Backend.Tests
{
    /// <summary>
    /// The Exports drive's "Generated by" shows the TradeNet user's full name; jobs store
    /// the JWT name claim, which is the user id.
    /// </summary>
    public class ExcelExportRequestedByNameTests
    {
        private static readonly IReadOnlyDictionary<string, string> Names =
            new Dictionary<string, string> { ["42"] = "Daw Aye Aye", ["7"] = " " };

        [Fact]
        public void A_known_user_id_shows_the_full_name()
            => Assert.Equal("Daw Aye Aye", ExcelExportController.DisplayName("42", Names));

        [Theory]
        [InlineData("99")]        // no such user
        [InlineData("admin")]     // an older job that stored a user name
        [InlineData("7")]         // a user row with a blank FullName
        public void Anything_unresolved_falls_back_to_the_stored_value(string stored)
            => Assert.Equal(stored, ExcelExportController.DisplayName(stored, Names));

        [Fact]
        public void A_job_with_no_requester_stays_empty()
            => Assert.Null(ExcelExportController.DisplayName(null, Names));
    }
}
