-- SUPERSEDED
-- Production report index deployment is centralized in:
-- StoredProcedureMigrations/IndexedMigrations/TradeNetReportIndexes_Production.sql
--
-- Run the canonical script manually in SSMS or Azure Data Studio.
-- This file intentionally performs no schema changes.
